### ISSUE TITLE
Add NFData instances

### ISSUE THREAD

**Issue by anfelor** [snowleopard/alga#54] opened 2018-03-29 21:48 UTC
While writing my [benchmark experiment](https://github.com/anfelor/graph-benchmarks) I noticed that no graph implementation but `data Graph` has a `NFData` instance. Is there a reason for this?

Adding them would for example provide a way to fully evaluate a `Relation a` without [relying on equality with itself](https://github.com/anfelor/graph-benchmarks/blob/12a0a46b1891fb402c663563c5874ea9a105e970/Common.hs#L28). The biggest design decision here seems to be the question of whether to evalute the `graphKL` field on `AdjacencyMap a`. On the one hand the docs clearly state that `rnf` should "fully evaluate all sub-components", but then the field is only meant to be cached for some computations that might not be needed. What do you think @snowleopard @nobrakal?

Related: #14

**Comment by nobrakal** [comment] 2018-03-30 07:47
I agree that having a `NFData` is a good idea. The problem is even more philosophical, what does it mean to "fully evaluate" a graph ?
Equality as you wrote? Or visiting each edge ? Each vertex ? Or maybe map or fold something on it ?
As a mathematical object, it is not clear at all to me...

**Comment by anfelor** [comment] 2018-03-30 08:13
> what does it mean to "fully evaluate" a graph?

It means to eliminate all lazy references from a data structure:
```haskell
> let x = Algebra.Graph.Relation.star 'a' "abcdefghij"
> :sprint x -- x is just a lazy reference at this moment
x = _
> Algebra.Graph.Relation.isEmpty  x
False
> :sprint x -- now the first field has been evaluated to normal form, but ...
x = Relation
      (containers-0.5.7.1:Data.Set.Base.Bin
         10 'g'
         (containers-0.5.7.1:Data.Set.Base.Bin
            6 'c'
            (containers-0.5.7.1:Data.Set.Base.Bin
               2 'b'
               (containers-0.5.7.1:Data.Set.Base.Bin
                  1 'a' containers-0.5.7.1:Data.Set.Base.Tip
                  containers-0.5.7.1:Data.Set.Base.Tip)
               containers-0.5.7.1:Data.Set.Base.Tip)
            (containers-0.5.7.1:Data.Set.Base.Bin
               3 'e'
               (containers-0.5.7.1:Data.Set.Base.Bin
                  1 'd' containers-0.5.7.1:Data.Set.Base.Tip
                  containers-0.5.7.1:Data.Set.Base.Tip)
               (containers-0.5.7.1:Data.Set.Base.Bin
                  1 'f' containers-0.5.7.1:Data.Set.Base.Tip
                  containers-0.5.7.1:Data.Set.Base.Tip)))
         (containers-0.5.7.1:Data.Set.Base.Bin
            3 'i'
            (containers-0.5.7.1:Data.Set.Base.Bin
               1 'h' containers-0.5.7.1:Data.Set.Base.Tip
               containers-0.5.7.1:Data.Set.Base.Tip)
            (containers-0.5.7.1:Data.Set.Base.Bin
               1 'j' containers-0.5.7.1:Data.Set.Base.Tip
               containers-0.5.7.1:Data.Set.Base.Tip)))
      _ -- ... the second is still a lazy reference
```

In practice that is easy to accomplish, since a lot of data structures like Sets already have NFData instances. So for example the one for `Relation a` would just be
```haskell
instance NFData a => NFData (Relation a) where
  rnf (Relation d r) = rnf d `seq` rnf r `seq` ()
```

**Comment by snowleopard** [comment] 2018-03-30 14:27
> I noticed that no graph implementation but `data Graph` has a `NFData` instance. Is there a reason for this?

@anfelor No, there is no particular reason. They are not there, because I didn't need them so far. And the instance for `data Graph` was contributed by @phadej if I remember correctly.

I don't mind adding these instances, but as you say, it may be non-obvious how to do that in some cases. 

One reason for not evaluating the field `graphKL` is that it is internal only -- one should not be able to extract it from an `AdjacencyMap`, so we could pretend that it is not there at all.

I'm not sure what is the cost of breaking the law that `rnf` should "fully evaluate all sub-components".

**Comment by anfelor** [comment] 2018-03-31 22:34
> Are there any known precedents?

No, as far as I know there aren't and google turned up nothing useful; only some opinions going in either way.

My two cents to this is that we should make a `NFData` instance that evaluates the `graphKL` field too, but add a comment suggesting to just use `seq` when concerned about space leaks since the first field is strict. That is in accord with `deepseq`'s philosophy of evaluating the whole structure and leads to predictable behavior of `dfs` and other algorithms (otherwise the first measurement would always be an outlier which makes reasoning about performance harder), but unfortunately also leaks the implementation detail of the first field being strict.

Another option would be to just add the `NFData` instance for `Relation` and leave the decision for `AdjacencyMap` to later. That might be better if the `dfs` and `scc` algorithms could be implemented without `graphKL` in the future and the first field might become lazy. But I believe that is relatively improbable and so I would opt for the first approach.

Happy Easter!

**Comment by snowleopard** [comment] 2018-03-31 22:57
> we should make a `NFData` instance that evaluates the `graphKL` field too

Consider `g = clique [1..1000] :: AdjacencyMap Int`. If you evaluate *all* `graphKL` fields of `g`, you'll create 1000 array-represented cliques *with no sharing between them*. That will surely dominate time and memory cost of `dfs` (and pretty much anything else), making benchmarking rather meaningless. 

Or I missing something?

**Comment by anfelor** [comment] 2018-04-01 11:44
> If you evaluate all graphKL fields

I don't really understand what you mean here, `AdjacencyMap a` has only one `graphKL` field?
I agree that a function like 
```haskell
strictClique :: Ord a => [a] -> AdjacencyMap a
strictClique = foldr (\ a b -> deepseq $ connect a b) empty . map (deepseq . vertex)
```
would show horrible performance, but if we create a `NFData` instance like
```haskell
instance Ord a => NFData (AdjacencyMap a) where
  rnf (AM a g) = a `seq` g `seq` ()
```
and call `g = deepseq $ clique [1..1000] :: AdjacencyMap Int` the performance impact should be rather small?

**Comment by anfelor** [comment] 2018-04-01 11:51
The `NFData` should probably be
```haskell
instance Ord a => NFData (AdjacencyMap a) where
  rnf (AM a g) = rnf (a, g)
```
Evaluating `graphKL` to weak head normal form wasn't what I intended.

**Comment by snowleopard** [comment] 2018-04-01 11:51
> I don't really understand what you mean here, `AdjacencyMap` a has only one `graphKL` field?

@anfelor Ah, indeed -- silly me. You are right, I confused this with an possible `AdjacencyMap` implementation discussed here: https://github.com/snowleopard/alga/issues/19#issuecomment-317714889. Here we would essentially have a cached `graphKL` field in every node of the graph expression. Presumably, we wouldn't want to evaluate every `graphKL` here, right?

**Comment by anfelor** [comment] 2018-04-01 11:58
> Presumably, we wouldn't want to evaluate every graphKL here, right?

Yes, of course. I have to admit though, that I didn't fully understand the reasoning behind that proposal, could you explain it a little further (in a separate issue maybe) if you plan to change the implementation in that direction?

**Comment by snowleopard** [comment] 2018-04-01 13:58
@anfelor Yes, good idea. I'll raise a separate issue to discuss an alternative implementation of `AdjacencyMap` based on tagged/parameterised graphs.

Coming back to the question of evaluating `graphKL` filed of the current implementation of `AdjacencyMap`:

Again, consider graph `g = clique [1..1000] :: AdjacencyMap Int`. Let's say we would like to benchmark a cheap function, such as `isEmpty`, `vertexCount` or `hasVertex`, on `g`. I believe that due to laziness, these functions do not require the evaluation of all O(n^2) edges of `g` and will therefore run O(n) time and memory. However, if you cause the evaluation of `graphKL` in these benchmarks, the time and memory consumption will be dominated by the construction of `graphKL`, which is O(n^2).

**Comment by snowleopard** [comment] 2018-04-01 14:08
In fact, we don't really want to fully evaluate the `adjacencyMap` field either in the above example. 

Perhaps, I'm misunderstanding the use of `rnf` in benchmarks: are you first going to fully evaluate an `AdjacencyMap` and only afterwards measure the performance of a function like `isEmpty`? If the answer is positive, then I think there is really no hard in fully evaluating everything.

**Comment by nobrakal** [comment] 2018-04-01 14:57
Concerning benchmarks, the NFData instance is only necessary for graph creation/modification. In fact, we only need it to fully evaluate the result of a function and thus avoid lazyness

**Comment by anfelor** [comment] 2018-04-01 15:25
>  Are you first going to fully evaluate an AdjacencyMap and only afterwards measure the performance of a function like isEmpty?

Yes, that's what I had in mind. Of course it will make the creation of an `AdjacencyMap` look a lot more expensive than it will be for most usecases, but maybe one could use a wrapper:
```haskell
newtype WHNF a = WHNF a
instance NFData (WHNF a) where
  rnf (WHNF a) = a `seq` () -- evaluate the contained data type to whnf instead of nf
```
Then one could benchmark both the behaviour of `AdjacencyMap a` and `WHNF (AdjacencyMap a)`.

> In fact, we don't really want to fully evaluate the adjacencyMap field either in the above example.

This is still possible, I think. As far as I know, if we test a function like `\n -> isEmpty $ clique [1..n] ` in criterion then the `Bool` of `isEmpty` will be evaluated to normal form, but the intermediate results of the function will not be stored. Maybe that is indeed the better approach.

> In fact, we only need it to fully evaluate the result of a function and thus avoid lazyness.

For this it is not necessary to use `NFData` since the first field of `AdjacencyMap` is strict, so just using `let !g = clique [1..1000] :: AdjacencyMap Int in g` already ensures that the `clique` function is called and all the graph constructors are converted to entries in our `AdjacencyMap`.

**Comment by anfelor** [comment] 2018-04-01 15:27
> Calling it on g is fine, but calling it on h leads to unnecessary evaluation of graphKL which will lead to overly pessimistic results for removeVertex. For h we only need fully evaluate the adjacencyMap field.

Ah, I didn't think about that at first. So for functions like that (where criterion evaluates the result to normal form) a wrapper like `WHNF` is crucial. So one wouldn't test `removeVertex 1 g`, but rather `WHNF $ removeVertex 1 g`.

**Comment by snowleopard** [comment] 2018-04-01 16:08
One more thought: fully evaluating `g`, including the `graphKL` field, will actually give an unfair advantage to functions like `dfs` :) Indeed, the cost of converting an `AdjacencyMap` to an array-based representation should very much be included into the cost of `dfs`, as otherwise we will only benchmark the `containers` library and not our wrapper.

**Comment by anfelor** [comment] 2018-04-01 16:28
> as otherwise we will only benchmark the containers library and not our wrapper.

Yes, I see. But if we benchmark `\n -> dfs $ clique [1..n]` then the `graphKL` field would be recomputed at every benchmark run, so we don't run into the problem, right?

When we have a huge graph build from a file though without `deepseq` and we benchmark `dfs` repeatedly on the same graph, the first run would be slow and the others would be faster, which makes the benchmark result depended on the number of runs. That sounds pretty bad to me.

The main reason, why I proposed to make the `NFData` instance evaluate the `graphKL` field too is because I thought `deepseq` was something used nearly only when trying to optimize performance and I believe there should be a function for evaluating the `graphKL` field. However, it is apparently not the right choice for evaluation of the graph as a benchmark result. I am not sure, if the problems we have with our benchmarks now are a symptom of a wrong instance or just a price we have to pay once for a better API. What do you think @snowleopard ?

**Comment by snowleopard** [comment] 2018-04-01 16:50
> if we benchmark `\n -> dfs $ clique [1..n]` then the `graphKL` field would be recomputed at every benchmark run, so we don't run into the problem, right?

There is still a problem! We want to measure the cost of `dfs` in isolation, not including the time it took to construct the adjacency map. We therefore need a function that *fully evaluates only* the `adjacencyMap` field of `AdjacencyMap`. I don't know how this function should be called, but it's likely not `rnf` from `NFData`. 

It may be best to include evaluation of the right part of the data structure into the benchmark generation function. We'll have something like `cliqueBenchmark :: Int -> AdjacencyMap Int` calling `clique [1..n]` and evaluating the `adjacencyMap` field of the resulting `AdjacencyMap`.

> I thought `deepseq` was something used nearly only when trying to optimize performance

If you need to optimise performance, then `rnf` or `deepseq` that includes `graphKL` will seldom be the right choice. It may be if you intend to call `dfs`, but it's definitely not if you intend to call `isEmpty` and many other functions that do not need `graphKL`.

**Comment by snowleopard** [comment] 2018-04-01 16:57
I'd argue that you never want to fully evaluate `graphKL`.

It's needed only for a few functions like `dfs`, and there is no point in evaluating it before calling `dfs`.

Functions like `rnf` and `deepseq` are typically used to prevent resource leaks in lazy IO programs, but `graphKL` can never lead to a resource leak: if you fully evaluate the `adjacencyMap` field, then you need no resource handles to compute `graphKL` from `adjacencyMap`. 

@anfelor @nobrakal Do you have *any* example use-case where it would be useful to define `rnf`, which evaluates `graphKL` field?

**Comment by anfelor** [comment] 2018-04-01 17:00
> We therefore need a function that fully evaluates only the adjacencyMap field of AdjacencyMap.

As that field is strict, I think that function should be `seq`. For example:
```haskell
> let g = Algebra.Graph.Class.clique  [1..3] :: AdjacencyMap Int
> :sprint g
g = _
> g `seq` ()
()
> :sprint g
g = Algebra.Graph.AdjacencyMap.Internal.AM
      (containers-0.5.7.1:Data.Map.Base.Bin
         3 2
         (containers-0.5.7.1:Data.Set.Base.Bin
            1 3 containers-0.5.7.1:Data.Set.Base.Tip
            containers-0.5.7.1:Data.Set.Base.Tip)
         (containers-0.5.7.1:Data.Map.Base.Bin
            1 1
            (containers-0.5.7.1:Data.Set.Base.Bin
               2 2 containers-0.5.7.1:Data.Set.Base.Tip
               (containers-0.5.7.1:Data.Set.Base.Bin
                  1 3 containers-0.5.7.1:Data.Set.Base.Tip
                  containers-0.5.7.1:Data.Set.Base.Tip))
            containers-0.5.7.1:Data.Map.Base.Tip
            containers-0.5.7.1:Data.Map.Base.Tip)
         (containers-0.5.7.1:Data.Map.Base.Bin
            1 3 containers-0.5.7.1:Data.Set.Base.Tip
            containers-0.5.7.1:Data.Map.Base.Tip
            containers-0.5.7.1:Data.Map.Base.Tip))
      _
```

> Do you have any example use-case where it would be useful to define rnf, which evaluates graphKL field?

Only the case of the first benchmark running slower.

**Comment by snowleopard** [comment] 2018-04-01 17:16
> Only the case of the first benchmark running slower.

I don't think it will be running "slower" with `rnf` defined to evaluate only `adjacencyMap`. It will be taking exactly the right time since evaluating `graphKL` is part of the job that `dfs` does.

Second/later benchmarks should somehow be put in exactly the same situation, where only  `adjacencyMap` field is evaluated, and `graphKL` is not.

**Comment by nobrakal** [comment] 2018-04-01 17:18
>Only the case of the first benchmark running slower.
@anfelor Sorry if it is obvious, but I don't understand why the first benchmark will run slower...

**Comment by snowleopard** [comment] 2018-04-01 17:24
@nobrakal In case another clarification is needed: Criterion runs several benchmarks by applying exactly the same function `f` to the same input `x`. If `x` is fully evaluated, then the function should always take exactly the same time, modulo some noise. However, in our case we do not want `x` to be fully evaluated: we want the `graphKL` field unevaluated, since it's part of `f`'s job! But then, the second run of the benchmark will be in a better situation: `graphKL` will be evaluated after the first run so it will have easier job to do. It's unclear what is the right way to solve this issue.

**Comment by anfelor** [comment] 2018-04-01 17:39
> I don't think it will be running "slower" with rnf defined to evaluate only adjacencyMap. It will be taking exactly the right time since evaluating graphKL is part of the job that dfs does.

I see your point and I agree that we could write a benchmark like that even if I don't like the result depending on the number of runs; is the number of times criterion runs a benchmark fixed?
That also has the additional advantage of being able to use lazyness in the benchmark, maybe dfs can already start while the `graphKL` field is being evaluated?

However, I believe that it should be possible to evaluate `graphKL` manually if it is a expensive operation (which it is going to be as graphs get bigger). If it is part of the `NFData` instance, then `deepseq` would be "deeper" that `seq` which feels right to me, but if you think otherwise I am fine with `rnf` being `seq` too.

> Second/later benchmarks should somehow be put in exactly the same situation, where only adjacencyMap field is evaluated, and graphKL is not.

I think that might be possible, but I don't have time to explore it now. If it is still relevant in a couple of days I could give it a try.

**Comment by snowleopard** [comment] 2018-04-01 18:03
I'm starting to think that the current implementation of `AdjacencyMap` with a cached `graphKL` field is just too magic. If it takes us so much time to understand how to benchmark it, it will likely be confusing for users too. Maybe we should just avoid such cached fields altogether.

**Comment by nobrakal** [comment] 2018-05-19 16:01
What is the status of this ? If `AdjacencyMap` is problem, is the NFData instance of `Relation` is one ?
The one proposed by @anfelor seems more than reasonnable:
> ```Haskell
>instance NFData a => NFData (Relation a) where
>  rnf (Relation d r) = rnf d `seq` rnf r `seq` ()
> ```

**Comment by snowleopard** [comment] 2018-05-19 21:37
@nobrakal Yes, this `Relation` instance looks fine. Feel free to send a PR!

**Comment by nobrakal** [comment] 2018-07-14 13:53
More and more tricky as I dig inside this ^^.

The current `deepseq` provide an other instance of `NFData (a -> b)` than the one discussed in the mail thread:
```Haskell
rwhnf = (`seq` ())

instance NFData (a -> b) where rnf = rwhnf
```
So it assume that the function is in `NF` when in `WHNF`. One of the problem I see is that it is not fully evaluating the vertices (contrary to the NFData instance of `Algebra.Graph`). One solution is to have:
```Haskell
instance NFData a => NFData (Fold a) where
    rnf = foldg () rnf (\a b -> rnf a `seq` rnf b) (\a b -> rnf a `seq` rnf b)
```
or
```Haskell
instance NFData a => NFData (Fold a) where
    rnf = fmap rnf
```
But I don't know at all if this make sense :p

**Comment by snowleopard** [comment] 2018-07-14 15:33
> But I don't know at all if this make sense :p

Same for me :D Could you do some experiments to figure out which implementation works best?

**Comment by nobrakal** [comment] 2018-07-16 16:39
Oops, of course `rnf = fmap rnf` doesn't type....

> Could you do some experiments to figure out which implementation works best?



So, as `Fold` is a function, it is already in NF, unsurprisingly:
```
> let x = clique [1..1000000] :: Fold Int
> x `seq` ()
()
(0.01 secs, 361,904 bytes)
```
Folding `rnf`:
```
>  foldg () rnf (\a b -> rnf a `seq` rnf b) (\a b -> rnf a `seq` rnf b) x
()
(1.65 secs, 521,590,728 bytes)
```

An other fold, more simple (and using less memory):
```
> foldg () rnf (\a b -> a `seq` b) (\a b -> a `seq` b) x
()
(1.67 secs, 496,364,128 bytes)
```

For the comparison
```
> let x = clique [1..1000000] :: Graph Int
> x `seq` ()
()
(0.00 secs, 361,824 bytes)
> foldg () rnf (\a b -> rnf a `seq` rnf b) (\a b -> rnf a `seq` rnf b) x
()
(1.92 secs, 475,328,584 bytes)
> foldg () rnf (\a b -> a `seq` b) (\a b -> a `seq` b) x
()
(1.54 secs, 448,369,608 bytes)
> x `deepseq` ()
()
(1.21 secs, 440,363,488 bytes)
```

So

```Haskell
instance NFData a => NFData (Fold a) where
    rnf = foldg () rnf (\a b -> a `seq` b) (\a b -> a `seq` b)
```

seems a reasonable option since it fully evaluate the leaves, and go through the graph quickly.

**Comment by nobrakal** [comment] 2018-07-16 17:19
> @nobrakal Thanks! I didn't really explain what I meant by experiments: I meant to measure performance of graph consumption algorithms: if they take longer, it means some extra work was needed. So you should pick the NFData instance which leads to fastest graph deconstruction.

I am not sure I understood what you meant. Were you saying that we should take the fastest implementation _in comparison_ of other graphs "consumer" ?

I have just benchmarked the function against one of the fastest "consumer" (and non-trivial), `hasVertex` and `size`. 

Using Criterion and a `Fold` clique with 100.000 vertices of type `Int`.

```
benchmarking "foldg () rnf (\a b -> a `seq` b `seq` ()) (\a b -> a `seq` b `seq` ()) x"
time                 6.644 ms   (6.623 ms .. 6.668 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 6.651 ms   (6.640 ms .. 6.664 ms)
std dev              35.32 μs   (28.14 μs .. 46.57 μs)

benchmarking "foldg () rnf (\a b -> rnf a `seq` rnf b `seq` ()) (\a b -> rnf a `seq` rnf b `seq` ()) x"
time                 6.995 ms   (6.751 ms .. 7.388 ms)
                     0.990 R²   (0.984 R² .. 0.998 R²)
mean                 6.840 ms   (6.768 ms .. 6.983 ms)
std dev              292.7 μs   (190.2 μs .. 423.2 μs)
variance introduced by outliers: 21% (moderately inflated)


benchmarking size
time                 20.42 ms   (20.02 ms .. 20.82 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 20.53 ms   (20.18 ms .. 21.11 ms)
std dev              1.065 ms   (611.2 μs .. 1.861 ms)
variance introduced by outliers: 18% (moderately inflated)

benchmarking hasVertex notIntTheGraph
time                 6.803 ms   (6.673 ms .. 7.058 ms)
                     0.996 R²   (0.991 R² .. 1.000 R²)
mean                 6.773 ms   (6.722 ms .. 6.905 ms)
std dev              205.5 μs   (29.39 μs .. 356.0 μs)
variance introduced by outliers: 13% (moderately inflated)
```

Again for the comparison, using `Algebra.Graph`

```
benchmarking deepseq
time                 1.173 ms   (1.168 ms .. 1.177 ms)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 1.147 ms   (1.137 ms .. 1.156 ms)
std dev              32.31 μs   (27.18 μs .. 36.69 μs)
variance introduced by outliers: 17% (moderately inflated)

benchmarking size
time                 2.296 ms   (2.255 ms .. 2.328 ms)
                     0.997 R²   (0.996 R² .. 0.999 R²)
mean                 2.333 ms   (2.283 ms .. 2.422 ms)
std dev              224.8 μs   (133.6 μs .. 391.8 μs)
variance introduced by outliers: 66% (severely inflated)

benchmarking hasVertex notInTheGraph
time                 1.187 ms   (1.183 ms .. 1.193 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 1.232 ms   (1.222 ms .. 1.240 ms)
std dev              32.33 μs   (30.26 μs .. 34.16 μs)
variance introduced by outliers: 14% (moderately inflated)
```

`hasVertex notInTheGraph` should be (and it is) pretty close, at least for object with cheap comparison (like Int), of `deepseq` since it need to fully evaluate everything and "unify" the results with very  fast operation (||).

**Comment by snowleopard** [comment] 2018-07-16 18:14
> I am not sure I understood what you meant. Were you saying that we should take the fastest implementation in comparison of other graphs "consumer" ?

OK, let me clarify. Why are we using `NFData` when benchmarking? Because we don't want the consumer (an algorithm) to spend time evaluating the input itself. We want to measure only the actual computation time. This means we can judge different implementations of `NFData` on whether they left any work to be done on evaluating the graph to the consumers. 

So, if you have candidate implementations `rnf1` and `rnf2`, you can compare them by seeing how they impact the benchmark suite. A trivial implementation `rnfTrivial _ = ()` should be the worst.

**Comment by nobrakal** [comment] 2018-07-18 10:51
Ok, thanks for the explanation, I see !

Here is a sample of a GHCi session, because I was not able to reproduce the time differences in the benchmarking suite (I believe that there is some evaluations hidden, or made by GHC in the constructed graph).

To show the differences, I am using `primesTo` from [haskell wiki](https://wiki.haskell.org/Prime_numbers#Sieve_of_Eratosthenes) which produce, lazily, the list of the primes up to a number.

`vertexCount` has to perform some comparison, so it is obviously faster if what it have to compare is already in normal form

So, using 
```Haskell
instance NFData a => NFData (Fold a) where
    rnf = foldg () rnf (\a b -> a `seq` b) (\a b -> a `seq` b)
```
```
> let x  = clique [primesTo 3000,primesTo 3000]
(0.01 secs, 407,144 bytes)
> rnf x
()
(0.67 secs, 845,576,656 bytes)
> vertexCount x
1
(0.01 secs, 406,544 bytes)
```

For comparison, using 
```Haskell
instance NFData a => NFData (Fold a) where
    rnf _ = ()
```
```
> let x  = clique [primesTo 3000,primesTo 3000]
(0.01 secs, 402,384 bytes)
> rnf x
()
(0.01 secs, 402,400 bytes)
> vertexCount x
1
(1.36 secs, 845,507,352 bytes)
```

After thinking a bit on it: ` foldg () rnf (\a b -> rnf a `seq` rnf b) (\a b -> rnf a `seq` rnf b)` is the same than the first solution, because `a` is already `()`, so using `rnf` on it will not produce anything magic.

**Comment by snowleopard** [comment] 2018-07-18 10:57
@nobrakal I'm a bit confused with your example: `clique [primesTo 3000,primesTo 3000]`. It's a very strange graph -- there is only one vertex (a list of prime numbers) with a selfloop?

**Comment by nobrakal** [comment] 2018-07-18 11:07
> Any reason why you chose it? 

It is very simple, and a comparison of the vertices needs some time to achieve. Nothing really more clever !

I didn't thought in term of graph, only in term of data structure.

**Comment by snowleopard** [comment] 2018-07-18 11:18
I see, but this makes the graph itself pretty small, so you really only measure the time it takes to evaluate vertices, not the graph structure itself. 

Could could do something like `fmap primesTo $ clique [primesTo 100]` to measure both :)

**Comment by nobrakal** [comment] 2018-07-18 12:58
Mmh I see.

Here are a test using `let x = fmap primesTo $ clique $ primesTo 1500` (was there a typo in your comment ?)

Using the `rnf = foldg () rnf (\a b -> a `seq` b) (\a b -> a `seq` b)`
```
> let x = fmap primesTo $ clique $ primesTo 1500
(0.01 secs, 403,080 bytes)
> rnf x
()
(3.40 secs, 7,206,218,496 bytes)
> vertexCount x
239
(0.02 secs, 537,352 bytes)
```

Using a trivial `rnf _ = ()`
```
> let x = fmap primesTo $ clique $ primesTo 1500
(0.02 secs, 420,816 bytes)
> rnf x
()
(0.01 secs, 425,272 bytes)
> vertexCount x
239
(3.23 secs, 7,335,645,664 bytes)
```

**Comment by snowleopard** [comment] 2018-07-18 13:58
@nobrakal Thanks, looks good!

So, are there only two candidates? If yes, feel free to proceed with your winner :)

**Comment by snowleopard** [comment] 2018-07-18 17:40
@nobrakal No, I don't have anything better :) Go ahead and add it.

**Comment by snowleopard** [comment] 2018-07-19 13:42
@nobrakal Thanks for taking care of `Fold`! For completeness we should probably also derive `NFData` instances for various `Relation`-based graph newtypes, e.g. see:

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Relation/InternalDerived.hs#L36

**Comment by nobrakal** [comment] 2018-07-21 09:58
So this now can be closed ?

**Comment by snowleopard** [comment] 2018-07-21 10:44
@nobrakal Yes, I think we've covered all graph data types. Closing.

**Closed by snowleopard** 2018-07-21 10:44 UTC
